[package]
name = "kingslayer"
version = "0.9.4"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
edition = "2018"
description = "A text adventure written in Rust"
license = "MIT"
readme = "README.md"
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"