[package]
name = "kingslayer"
version = "0.4.2"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A text adventure dungeon crawler game written in Rust"
readme = "README.md"
repository = "https://github.com/Maxgy/kingslayer"
keywords = ["text", "adventure", "game", "dungeon", "crawler"]
categories = ["games", "game-engines"]
exclude = ["*.yml"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ron = "0.5"
serde_json = "1.0"
rand = { version = "0.6", features = ["wasm-bindgen"] }

[lib]
crate-type = ["rlib"]
