[package]
name = "kingslayer"
version = "0.10.0"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A text adventure written in Rust"
readme = "README.md"
repository = "https://github.com/Maxgy/kingslayer"
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"