[package]
name = "kinggame1d"
version = "0.8.0"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
description = "A text-based adventure written in Rust"
readme = "README.md"
license = "MIT"
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"