[package]
name = "kinggame1d"
version = "0.4.4"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
description = "A text-based adventure written in Rust"
readme = "README.md"
license = "MIT"
publish = false

[dependencies]
